name = "Nyampack"
author = "pdewebq"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86b301653bf6615a27d4ce5a487fd5b7e14d0dbd134b6d7b853787237d756e0e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
