name = "Nyampack"
author = "pdewebq"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be2bef2f4e47699eade0658af0ac07b4c17cbc41b5806d04c7496efde7fa8bf4"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
