name = "Nyampack"
author = "pdewebq"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bd4d3dcf9ba7baf3ecac8194b8bd098c7660bc58664d369f36063181a0a898c"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
