name = "Nyampack"
author = "pdewebq"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96fdbc4488d766c21cdf29e07f647f70b4e5dcb01721d1a38c452c7f46fbd3f1"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
