name = "Nyampack"
author = "pdewebq"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aed7a2f913a5c1ac946f395ed87708f9a20bec14bf2b26d58386bc800522f967"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
