name = "Nyampack"
author = "pdewebq"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79f918f6f6bd699cd65f948d01afe76b24d72c5794a5b43b43e94085481c542b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
