name = "Nyampack"
author = "pdewebq"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a38664d3dc13fdbce2baf3a2612e465d61a3da1d59c79789efea83af8add14af"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
