name = "Nyampack"
author = "pdewebq"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aebbb0a6266564957ea6419b0fea89f2d9438cb916dc1acca3cdcc76c611981e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
