name = "Nyampack"
author = "pdewebq"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "400b48a292fc097b92370758e667072beb35e17c73984cd78d75a7069e77bfdb"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
