name = "Nyampack"
author = "pdewebq"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53451c6e55b16c83d90241fe749686ff1026e24f9026b7caa0c0c79cca4af303"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
