name = "Nyampack"
author = "pdewebq"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f01ad94e56586805a4ff2ab1bfe3fefb699f7322f96314071363a4b3cfc7d463"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
